<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AZMAL" failures="1" tests="8" name="SanityTest" time="53.427" errors="0" timestamp="2022-09-20T17:59:14 IST">
  <testcase classname="ebankingLoginTest.EBankingLoginTest" name="testResetUserIdAndpassword" time="0.438"/>
  <testcase classname="ebankingLoginTest.EBankingLoginTest" name="testLoginWithValidUserIdAndPassword" time="2.617"/>
  <testcase classname="ebankingLoginTest.EBankingLoginTest" name="testLogoutFromAccount" time="0.791"/>
  <testcase classname="ebankingPracticeTest.AddNewCustomerTest" name="testAddNewCustomerFieldsWithValidDetails" time="7.215"/>
  <testcase classname="ebankingPracticeTest.NewAccountTest" name="testNewAccountWithInvalidData" time="4.797"/>
  <testcase classname="ebankingPracticeTest.NewAccountTest" name="testNewAccountWithValidData" time="3.837">
    <failure type="java.lang.AssertionError" message="Exception occured while testing testNewAccountWithValidData:[Ljava.lang.StackTraceElement;@59096b66">
      <![CDATA[java.lang.AssertionError: Exception occured while testing testNewAccountWithValidData:[Ljava.lang.StackTraceElement;@59096b66
at ebankingPracticeTest.NewAccountTest.testNewAccountWithValidData(NewAccountTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testNewAccountWithValidData -->
  <testcase classname="ebankingPracticeTest.DepositTest" name="testDepositWithInvalidData" time="7.751"/>
  <testcase classname="ebankingPracticeTest.DepositTest" name="testDepositWithValidData" time="1.807"/>
</testsuite> <!-- SanityTest -->
